import unittest
import data_loader
import os

FILE_PATH = os.path.dirname(os.path.abspath(__file__)) # set absolute path to .py

class TestDataLoader(unittest.TestCase):
    def test_load_csv(self):
        file_path = os.path.join(FILE_PATH, f'./temp-files/lyrics-data-2.csv')
        result = [{'artist_link': '/suicideboys/', 'song_name': 'Center Core Never More', 'song_link': '/center-core-never-more/', 'lyric': 'You did good, $lick\nIt\'s a smash\n(Smoke that pound, \'nother pound)\n(Smoke that pound, \'nother)\n(Smoke that pound, \'nother pound)\n(Takin\' a sip from the)\n(Smoke that pound, \'nother pound)\n(Smoke that pound, \'nother)\nDiamonds hit like Pop Rocks, we got too hot, lightin\' blunts with lava\nWe don\'t do the drama, but the Oscars where I\'m posted at\nGrammys on my neck, shoot for the stars, I swear to God on that\nI\'ma need you to stand on that, I\'m tryna tap in with your almanac\nWavy homies hated, I got demons in my basement\nNigga might piss me off, I\'ma lay his ass down on the pavement\nDreads swangin\', smokin\' Jamaican, lookin\' for all my payments\nPaper chasin\', Haitian, move the chains like fourth and inches\n(Bad shit), I\'m here to slay \'em\nAll this lean, bitch, I can\'t feel my body (yeah, yeah)\nAll these pills, bitch, I can\'t feel my body (yeah, yeah)\nAin\'t no love in my heart, I don\'t feel nobody (ah)\nKeep it to myself, I might lose it, can\'t catch a body\nWhite dove, fly high, throw my threes up in the sky\nThrow my threes around my eyes and then I call it my disguise\nMasked off, I\'m just out here with a raw face\nAsk me how I been and I draw blanks\nHold tight \'til my claws break\nFull metal jacket kinda heavy (heavy)\nAt the bottom of the fuckin\' lake, I parked my Chevy\n(Yeah) waiting to die but I wasn\'t born ready (nah)\nShaking up my life, I\'m just tryna hold steady\nBirds of a feather flock together (yeah)\nGrey the fucking gang, ain\'t no one could do it better (Grey)\nTwo odd numbers right behind the fucking letter\nMe, $lick and Germ our alliance is forever\nI just popped a pill (pill), pull up with the deal (deal)\nPistol whip a pussy, have \'em looping on the reel (reel)\nWood-grain wheel (wheel), chromed out rims (rim)\nMillion dollar deals, sign my name as "H-I-M" (wetto)\nTales from the North (North), back from the dead\nHard to feel for a pussy when these thorns in my hand (Northside)\nTwo story grave (grave), trauma on my wrists (wrist)\nThree fingers high, other three in my bitch (bitch)\nI got problems that won\'t go away (guess who?)\nDon\'t understand \'cause I been hitting pay (yeah)\nLord, I pray that my bitch gay (I just want a threesome)\nNew opps but my clique Grey (Grey)', 'language': 'en'}]
        self.assertEqual(data_loader.load_csv(file_path)[0], 2, 'CSV is not loading correctly')
        self.assertEqual(data_loader.load_csv(file_path)[1], result, 'CSV is not loading correctly')        

    def test_link_songs_with_artists(self):
        lyrics = [{'artist_link': '/ivete-sangalo/', 'song_name': 'Arerê', 'song_link': '/ivete-sangalo/arere.html', 'lyric': 'Tudo o que eu quero nessa vida,\nToda vida, é\nÉ amar você\nAmar você\n\nO seu amor é como uma chama acesa\nQueima de prazer\nDe prazer\n\nEu já falei com Deus que não vou te deixar\nVou te levar pra onde for\nQualquer lugar\nJá fiz de tudo pra não te perder\n\nArerê,\nUm lobby, um hobby, um love com você\nArerê,\nUm lobby, um hobby, um love com você\n\nCai, cai, cai, cai, cai pra cá\nHey, hey, hey\nTu-do,tu-do, vai rolar', 'language': 'pt'},
                 {'artist_link': '/ivete-sangalo/', 'song_name': 'Se Eu Não Te Amasse Tanto Assim', 'song_link': '/ivete-sangalo/se-eu-nao-te-amasse-tanto-assim.html', 'lyric': 'Meu coração\nSem direção\nVoando só por voar\nSem saber onde chegar\nSonhando em te encontrar\nE as estrelas\nQue hoje eu descobri\nNo seu olhar\nAs estrelas vão me guiar\n\nSe eu não te amasse tanto assim\nTalvez perdesse os sonhos\nDentro de mim\nE vivesse na escuridão\nSe eu não te amasse tanto assim\nTalvez não visse flores\nPor onde eu vi\nDentro do meu coração\n\nHoje eu sei\nEu te amei\nNo vento de um temporal\nMas fui mais\nMuito além\nDo tempo do vendaval\nNos desejos\nNum beijo\nQue eu jamais provei igual\nE as estrelas dão um sinal\n\nSe eu não te amasse tanto assim\nTalvez perdesse os sonhos\nDentro de mim\nE vivesse na escuridão\nSe eu não te amasse tanto assim\nTalvez não visse flores\nPor onde eu vi\nDentro do meu coração...', 'language': 'pt'}]
        artists = [{'name': 'Ivete Sangalo', 'genres': ['Pop', ' Axé', ' Romântico'], 'songs': 313, 'popularity': 4.4, 'link': '/ivete-sangalo/'}]
        result = [{'artist_link': '/ivete-sangalo/', 'song_name': 'Arerê', 'song_link': '/ivete-sangalo/arere.html', 'lyric': 'Tudo o que eu quero nessa vida,\nToda vida, é\nÉ amar você\nAmar você\n\nO seu amor é como uma chama acesa\nQueima de prazer\nDe prazer\n\nEu já falei com Deus que não vou te deixar\nVou te levar pra onde for\nQualquer lugar\nJá fiz de tudo pra não te perder\n\nArerê,\nUm lobby, um hobby, um love com você\nArerê,\nUm lobby, um hobby, um love com você\n\nCai, cai, cai, cai, cai pra cá\nHey, hey, hey\nTu-do,tu-do, vai rolar', 'language': 'pt', 'artist': {'name': 'Ivete Sangalo', 'genres': ['Pop', ' Axé', ' Romântico'], 'songs': 313, 'popularity': 4.4, 'link': '/ivete-sangalo/'}},
                 {'artist_link': '/ivete-sangalo/', 'song_name': 'Se Eu Não Te Amasse Tanto Assim', 'song_link': '/ivete-sangalo/se-eu-nao-te-amasse-tanto-assim.html', 'lyric': 'Meu coração\nSem direção\nVoando só por voar\nSem saber onde chegar\nSonhando em te encontrar\nE as estrelas\nQue hoje eu descobri\nNo seu olhar\nAs estrelas vão me guiar\n\nSe eu não te amasse tanto assim\nTalvez perdesse os sonhos\nDentro de mim\nE vivesse na escuridão\nSe eu não te amasse tanto assim\nTalvez não visse flores\nPor onde eu vi\nDentro do meu coração\n\nHoje eu sei\nEu te amei\nNo vento de um temporal\nMas fui mais\nMuito além\nDo tempo do vendaval\nNos desejos\nNum beijo\nQue eu jamais provei igual\nE as estrelas dão um sinal\n\nSe eu não te amasse tanto assim\nTalvez perdesse os sonhos\nDentro de mim\nE vivesse na escuridão\nSe eu não te amasse tanto assim\nTalvez não visse flores\nPor onde eu vi\nDentro do meu coração...', 'language': 'pt', 'artist': {'name': 'Ivete Sangalo', 'genres': ['Pop', ' Axé', ' Romântico'], 'songs': 313, 'popularity': 4.4, 'link': '/ivete-sangalo/'}}]
        self.assertEqual(data_loader.link_lyrics_with_artists(lyrics, artists), result, 'Wrong link of the data')    

unittest.main()